export const UI_LABELS = {
  totalPosts: "전체",
  activeTag: "선택 태그",
  activeSearch: "검색어",
  clearFilter: "태그 선택 해제",
  clearSearch: "검색 해제",
  allPosts: "모든 게시물",
  searchPlaceholder: "제목, 설명, 태그 검색",
  searchButton: "검색",
  tags: "태그",
  showAllTags: "모두 보기",
  showTopTags: "일부 보기",
  noPostsPrefix: "조건에 맞는 게시물이 없습니다:",
  page: "페이지",
  previous: "이전",
  next: "다음",
  archive: "아카이브",
  newer: "이전 글",
  older: "다음 글",
  contents: "목차",
} as const;
